-- AI 점심 큐레이터 스키마 (Oracle XE 21c)
-- db.init_schema() 가 세미콜론 단위로 한 문장씩 실행한다.

CREATE TABLE LUNCH_MENU (
    ID                 NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MENU_DATE          DATE NOT NULL UNIQUE,
    MENU_HASH          VARCHAR2(64) NOT NULL,
    MENUS              CLOB NOT NULL CONSTRAINT CK_LUNCH_MENUS_JSON CHECK (MENUS IS JSON),
    AI_SUMMARY         CLOB,
    ESTIMATED_CALORIES NUMBER,
    TAGS               CLOB CONSTRAINT CK_LUNCH_TAGS_JSON CHECK (TAGS IS JSON),
    RECOMMENDATION     CLOB,
    IMAGE_URL          VARCHAR2(500),
    CREATED_AT         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE MENU_IMAGE_CACHE (
    ID         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MENU_HASH  VARCHAR2(64) NOT NULL UNIQUE,
    IMAGE_URL  VARCHAR2(500) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- 자주 나온 메뉴 집계용 (GROUP BY)
CREATE TABLE MENU_ITEM (
    ID        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MENU_DATE DATE NOT NULL,
    DISH_NAME VARCHAR2(200) NOT NULL,
    CONSTRAINT FK_MENU_ITEM_DATE FOREIGN KEY (MENU_DATE)
        REFERENCES LUNCH_MENU (MENU_DATE) ON DELETE CASCADE
);

CREATE INDEX IX_LUNCH_MENU_HASH ON LUNCH_MENU (MENU_HASH);
CREATE INDEX IX_MENU_ITEM_DATE ON MENU_ITEM (MENU_DATE);
CREATE INDEX IX_MENU_ITEM_DISH ON MENU_ITEM (DISH_NAME);
